from deepsudoku.supervised_learning.doublesoftmax import SudokuDoubleSoftmaxLayer
from deepsudoku.supervised_learning.winrate import SudokuWinRate
from deepsudoku.supervised_learning.wrapper import SudukoWrapper

