python ppo_script.py \
    --exp-name AnealLR \
    --mask-actions True \
    --agent SeperateOnlyConv \
    --eval-freq 50 \
    --eval-steps 100 \
    --anneal-lr True \
    --use-random-starting-point True \
    --cut-off-limit 20 \
    --win-reward 3 \
    --fail-penalty 1 \
    --total-timesteps 10000000 \
    --ckpt-dir-load ckpt/Sudoku-nostop0__HigherPunishment__1__1693503354/18883584.pth